version: '3.9'

services:
  celery:
    image: lab1_django:latest
    command: celery -A exchanger.celery worker -Q default --loglevel=info
    volumes:
      - ../:/code
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=lab1.settings

  celery_email:
    image: lab1_django:latest
    command: celery -A exchanger.celery worker -Q email_queue --loglevel=info
    volumes:
      - ../:/code
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=lab1.settings
